# Generated by Django 3.2 on 2021-05-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
