# Generated by Django 3.2 on 2021-07-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
