# Generated by Django 3.2 on 2021-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='Payment', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='Chose size', max_length=100),
        ),
    ]
