# Generated by Django 3.2 on 2021-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210723_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.CharField(choices=[('INP', 'Inpost'), ('ODB', 'Odbiór'), ('PAC', 'Paczkomat')], default='None', max_length=10),
        ),
    ]
