# Generated by Django 3.2 on 2021-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
