# Generated by Django 3.2 on 2021-08-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default='5', max_digits=2, null=True),
        ),
    ]
