# Generated by Django 3.2 on 2021-08-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
