# Generated by Django 3.2 on 2021-08-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_phi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phi',
        ),
    ]
