# Generated by Django 3.2 on 2021-08-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_remove_order_phi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default='', max_length=200),
        ),
    ]
