# Generated by Django 3.2 on 2021-08-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
