# Generated by Django 3.2 on 2021-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quant',
            field=models.DecimalField(decimal_places=3, default='', max_digits=10),
        ),
    ]
