# Generated by Django 3.2 on 2021-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_order_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quant',
            field=models.DecimalField(decimal_places=3, default='5', max_digits=10),
        ),
    ]
