# Generated by Django 3.2 on 2021-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_order_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
