# Generated by Django 3.2 on 2021-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_order_quant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quant',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='', max_length=200),
        ),
    ]
