# Generated by Django 3.2 on 2021-08-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_remove_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='', max_length=200),
        ),
    ]
