# Generated by Django 3.2 on 2021-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
