# Generated by Django 3.2 on 2021-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_order_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ilosc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
