# Generated by Django 3.2 on 2021-08-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_order_ilosc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
