# Generated by Django 3.2 on 2021-08-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20210830_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
