# Generated by Django 3.2.8 on 2021-11-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20210830_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paczkomat',
            field=models.CharField(default='', max_length=200),
        ),
    ]
