# Generated by Django 3.2.8 on 2021-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_order_paczkomat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paczkomat',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='paczkomat',
            field=models.CharField(default='', max_length=800),
        ),
    ]
