# Generated by Django 3.2.8 on 2021-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_auto_20211104_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paczkomat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='paczkomat',
            field=models.CharField(default='', max_length=100),
        ),
    ]
